services:
  postgres:
    image: postgres:16
    networks:
      - backend
    environment:
      POSTGRES_DB: image_search
      POSTGRES_USER: image_search
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data_postgres:/var/lib/postgresql/data
  redis:
    image: redis:7
    networks:
      - backend

  nginx:
    image: nginx:alpine
    networks:
      - frontend
      - appnet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  app:
    build: ./app
    networks:
      - appnet
      - backend

networks:
  frontend:
    driver: bridge
  appnet:
    driver: bridge
  backend:
    driver: bridge

volumes:
  data_postgres:
